controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true


    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    mec_cont:
      type: mecanum_drive_controller/MecanumDriveController


mec_cont:
  ros__parameters:
    reference_timeout: 1.0 # max time between command messages before the vehicle should stop
    front_left_wheel_command_joint_name: 'Wheel_motor_2_Revolute_105'
    front_right_wheel_command_joint_name: 'Wheel_motor_4_Revolute_106'
    rear_right_wheel_command_joint_name: 'Wheel_motor_1_Revolute_107'
    rear_left_wheel_command_joint_name: 'Wheel_motor_3_Revolute_108'
    kinematics:
        base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
        wheels_radius: 0.075
        sum_of_robot_center_projection_on_X_Y_axis: 0.5245
    base_frame_id: 'base_footprint'
    odom_frame_id: 'odom'
    enable_odom_tf: true
    use_stamped_vel: false


